//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAMABGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAMABGUI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Msg001 {
            get {
                return ResourceManager.GetString("Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load setting file.
        /// </summary>
        internal static string Msg002 {
            get {
                return ResourceManager.GetString("Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save setting file.
        /// </summary>
        internal static string Msg003 {
            get {
                return ResourceManager.GetString("Msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect.
        /// </summary>
        internal static string Msg004 {
            get {
                return ResourceManager.GetString("Msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection error.
        /// </summary>
        internal static string Msg005 {
            get {
                return ResourceManager.GetString("Msg005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get value error.
        /// </summary>
        internal static string Msg006 {
            get {
                return ResourceManager.GetString("Msg006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value error.
        /// </summary>
        internal static string Msg007 {
            get {
                return ResourceManager.GetString("Msg007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to exit?.
        /// </summary>
        internal static string Msg008 {
            get {
                return ResourceManager.GetString("Msg008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        internal static string Msg009 {
            get {
                return ResourceManager.GetString("Msg009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drift mode error.
        /// </summary>
        internal static string Msg010 {
            get {
                return ResourceManager.GetString("Msg010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the power supply is &quot;ON&quot; for at least 60 seconds before trying to connect to the YAMAB.
        ///Press &quot;OK&quot; to connect.
        /// </summary>
        internal static string Msg011 {
            get {
                return ResourceManager.GetString("Msg011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Msg012 {
            get {
                return ResourceManager.GetString("Msg012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is valid only in &quot;Gun Slave&quot; mode..
        /// </summary>
        internal static string Msg013 {
            get {
                return ResourceManager.GetString("Msg013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not perform test. see details.
        /// </summary>
        internal static string Msg014 {
            get {
                return ResourceManager.GetString("Msg014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Test not completed.
        /// </summary>
        internal static string Msg015 {
            get {
                return ResourceManager.GetString("Msg015", resourceCulture);
            }
        }
    }
}
